### ISSUE TITLE
403 error scraping xenforo2 forum

### ISSUE THREAD

**Issue by ipkpjersi** [TUVIMEN/forumscraper#1]
Here is the syntax I am using via command-line:

```
forumscraper -A "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" --cookies '{"xf_tfa_trust": "TFATRUSTHERELOL", "xf_csrf": "CSRFHERELOL", "xf_user": "USERHERELOL", "xf_session": "SESSIONHERELOL", "bb_sessionhash": "SESSIONHASHHERELOL", "bb_lastvisit": "NUMBERSHERELOL", "bb_lastactivity": "0"}' xenforo2 https://rune-server.org/forums/informative-threads.656/
```

What am I doing wrong? I redacted any sensitive info btw but you get the idea. I'm pretty sure my cookies format is correct and so is my user agent.

**Comment by TUVIMEN** [comment]
Well, testing this site i have noticed that this site is using cloudflare, and when `curl -D - "https://rune-server.org/threads/the-player-updating-procedure.125681/"` command is run you get 403. Based on that and how my scraper retries after certain amount of requests i would say you just get blocked by cloudflare. In that case you should consider using `--wait` and `--random-wait`.

Note that for me this site doesn't have any problems being scraped without custom user-agent or cookies, even running the exact command you have given me works. I'd say that cloudflare is more aggressive for you based on your region.

It also might be the case that site denies you access to reactions or user info, see if this works in your browser, but i don't think it's really valuable data, you can disable them with `--nousers` and `--noreactions` if you want to save time or just ignore the errors.

**Comment by ipkpjersi** [comment]
That's some really good information, I appreciate it, thanks. It's really weird since I'm literally just on my home connection, it's an entirely residential connection so it shouldn't look suspicious at all but oh well.

I suppose I'm at the mercy of Cloudflare then, and my only other options would be something like looking into Cloudflare proxies or other ways to have Cloudflare not hate me.

In a way I feel better that I wasn't doing anything wrong, but yeah I guess it's not going to be as simple as I would have hoped for. lol

I'll go ahead and mark this as closed since it's not a problem with this program, thanks again.
