### ISSUE TITLE
Xenforo2 duplicate date

### ISSUE THREAD

**Issue by KaneTW** [TUVIMEN/forumscraper#2]
Some Xenforo2 installations (likely due to the threadmark extension) have the datetime field occur twice in a post. An example can be seen in this post: `https://forum.questionablequesting.com/threads/general-chat-thread.2746/page-93#post-1243409`

This causes the date field in the JSON to be populated twice.

**Comment by TUVIMEN** [comment]
It's [fixed](https://github.com/TUVIMEN/forumscraper/commit/5da5028b9932ad7634bc4a4d709a9342a3fc75f7), at least for this example.
